server:
  port: 8189
  servlet:
    context-path: /web-market-core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online_store?currentSchema=core_service_db
    username: postgres
    password: 333
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
