server:
  port: 8187
  servlet:
    context-path: /web-market-cart
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  cache:
    default:
      expire-time: 700000000
    user:
      expire-time: 700000000
      name: "Cart"
  kafka:
    consumer:
      group-id: 111
    bootstrap-servers: localhost:9092
    topic: "order_topic"
